### ISSUE TITLE
CLI: TypeError: Set is not a function or its return value is not iterable on some pages

### ISSUE THREAD

**Issue by pylebecq** [gildas-lormeau/SingleFile#607]
Hey 👋 . Thanks for your work on SingleFile, it is really useful!

**Describe the bug**
When using the CLI, and trying to save the Dropbox homepage, there is the following error:
<details>
  <summary>Stack: Error: Evaluation failed: TypeError: Set is not a function or its return value is not iterable</summary>

```
URL: https://www.dropbox.com/
Stack: Error: Evaluation failed: TypeError: Set is not a function or its return value is not iterable
    at getUrlFunctions (<anonymous>:8660:15)
    at Function.resolveStylesheetURLs (<anonymous>:8199:25)
    at <anonymous>:7476:36
    at NodeList.forEach (<anonymous>)
    at Processor.resolveStyleAttributeURLs (<anonymous>:7471:41)
    at Runner.executeTask (<anonymous>:6873:39)
    at <anonymous>:6837:11
    at Array.forEach (<anonymous>)
    at Runner.executeStage (<anonymous>:6829:28)
    at Runner.initialize (<anonymous>:6765:15)
    at ExecutionContext._evaluateInternal (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExecutionContext.evaluate (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)
    at async getPageData (/usr/src/app/node_modules/single-file/cli/back-ends/puppeteer.js:129:10)
    at async Object.exports.getPageData (/usr/src/app/node_modules/single-file/cli/back-ends/puppeteer.js:47:10)
    at async capturePage (/usr/src/app/node_modules/single-file/cli/single-file-cli-api.js:246:20)
    at async runNextTask (/usr/src/app/node_modules/single-file/cli/single-file-cli-api.js:167:20)
    at async Promise.all (index 0)
    at async capture (/usr/src/app/node_modules/single-file/cli/single-file-cli-api.js:118:2)
```
</details>

**To Reproduce**
1. Run the following command to get the latest docker image: `docker pull capsulecode/singlefile`
2. Run the following command to save the page: `docker run --rm capsulecode/singlefile https://www.dropbox.com/`
3. See error

Additional notes: Same error when doing a manual install.

**Expected behavior**
I expected the HTML content of the page to be printed in the terminal.

**Screenshots**

**Environment**
 - OS: macOS Catalina 10.15.7
 - Browser: Don't know what is included in the Docker image. When doing a manual install, I used Google Chrome.
 - Version: 88.0.4324.96 (Official Build) (x86_64)

**Additional Context**
Using the browser extension in Google Chrome works fine.

**Comment by gildas-lormeau** [comment]
Thank you for having reported the issue. I don't know why but this page overrides `Map` and `Set` with incorrect implementations when the page is loaded in headless mode. This issue is fixed in the last version.

**Comment by pylebecq** [comment]
Waow, that was quick. Thank you! ♥️
